name: bonedigger

on:
  issues:
    types: [opened, labeled, closed]
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 9 * * *'

permissions:
  issues: write
  contents: read

jobs:
  bonedigger:
    uses: projectbluefin/bonedigger/.github/workflows/lifecycle.yml@e75e3d2c7e21e72b887cad84f4723e10a9133d16 # main
    with:
      brand_name: "Bluefin"
      brand_emoji: "🦖"
    secrets: inherit
