name: bonedigger

on:
  issues:
    types: [opened, labeled, closed]
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 9 * * *'

permissions:
  issues: write
  contents: read

jobs:
  bonedigger:
    uses: projectbluefin/bonedigger/.github/workflows/lifecycle.yml@1b4b8265016cf33ad2dd86e40b0222266be9ce63 # main
    with:
      brand_name: "Bluefin"
      brand_emoji: "🦖"
    secrets: inherit
